// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNH-FfvWJJDHlQ7QcFjrmdgb9NqBkdIm8',
    appId: '1:966336127801:web:7b390ff45b68cfdc623ee8',
    messagingSenderId: '966336127801',
    projectId: 'qrcode-82a04',
    authDomain: 'qrcode-82a04.firebaseapp.com',
    storageBucket: 'qrcode-82a04.appspot.com',
    measurementId: 'G-QCF89TF3VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkcuWuq-KiDCERT75pIqd4tURjGo9AGg',
    appId: '1:966336127801:android:e2e9ff8b7e828dae623ee8',
    messagingSenderId: '966336127801',
    projectId: 'qrcode-82a04',
    storageBucket: 'qrcode-82a04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv0r-776Gb984YDc-Y91oxfXieKslind0',
    appId: '1:966336127801:ios:fb424ba7e59bb41b623ee8',
    messagingSenderId: '966336127801',
    projectId: 'qrcode-82a04',
    storageBucket: 'qrcode-82a04.appspot.com',
    iosClientId: '966336127801-0pb2d8i0d8m2rlr84ns9l073q9shhuvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv0r-776Gb984YDc-Y91oxfXieKslind0',
    appId: '1:966336127801:ios:fb424ba7e59bb41b623ee8',
    messagingSenderId: '966336127801',
    projectId: 'qrcode-82a04',
    storageBucket: 'qrcode-82a04.appspot.com',
    iosClientId: '966336127801-0pb2d8i0d8m2rlr84ns9l073q9shhuvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCodeFirebase',
  );
}
